'use client';

import { useCallback, useEffect, useState } from 'react';
import DOMPurify from 'dompurify';
import * as api from '../src/services/api';

const formatDate = (value) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '';
const sender = (message) => message.from?.emailAddress?.name || message.from?.emailAddress?.address || 'Remetente desconhecido';
const textOf = (message) => `${message.subject || ''}\n${message.bodyPreview || ''}\n${message.body?.content || ''}`;
const isRedCategory = (category) => category === 'spam' || category === 'promocoes';

function AuthPanel({ onAuthenticated }) {
  const [loading, setLoading] = useState(false), [info, setInfo] = useState(null), [error, setError] = useState('');
  const login = async () => { setLoading(true); setError(''); try { const result = await api.startDeviceCode(); if (!result?.userCode) throw new Error(result?.error || 'Código não retornado.'); setInfo(result); const timer = setInterval(async () => { const s = await api.status(); if (s.authenticated) { clearInterval(timer); setInfo(null); onAuthenticated(); } }, 2500); setTimeout(() => clearInterval(timer), 900000); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  return <section className="auth-card"><div className="eyebrow">OUTLOOK / HOTMAIL</div><h1>Caixa de entrada, sem ruído.</h1><p>Conecte sua conta Microsoft e ensine o classificador com um clique sempre que uma mensagem for propaganda.</p><button className="primary" onClick={login} disabled={loading}>{loading ? 'Gerando código…' : 'Conectar conta Microsoft'}</button>{info?.userCode && <div className="code-box"><strong>{info.userCode}</strong><span>{info.message}</span><a href={info.verificationUri} target="_blank" rel="noreferrer">Abrir microsoft.com/devicelogin</a></div>}{error && <p className="error">{error}</p>}</section>;
}

export default function Page() {
  const [auth, setAuth] = useState(null), [messages, setMessages] = useState([]), [selected, setSelected] = useState(null), [predictions, setPredictions] = useState({}), [learning, setLearning] = useState(null), [loading, setLoading] = useState(false), [bulkDeleting, setBulkDeleting] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const classifyMessages = async (items) => { const results = await Promise.all(items.map(async (m) => [m.id, await api.classify(textOf(m))])); setPredictions(Object.fromEntries(results)); };
  const load = useCallback(async () => { setLoading(true); setError(''); try { const items = await api.listMessages(); setMessages(items); await classifyMessages(items); setLearning(await api.learningStatus()); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { api.status().then(setAuth).catch(() => setAuth({ authenticated: false })); }, []);
  useEffect(() => { if (auth?.authenticated) load(); }, [auth, load]);
  const open = async (id) => { try { setSelected({ ...(await api.getMessage(id)), ...(predictions[id] ? { classification: predictions[id] } : {}) }); } catch (e) { setError(e.message); } };
  const remove = async (id) => { if (!window.confirm('Excluir este e-mail permanentemente?')) return; try { await api.deleteMessage(id); setMessages((all) => all.filter((m) => m.id !== id)); if (selected?.id === id) setSelected(null); } catch (e) { setError(e.message); } };
  const teach = async (message, label = 'promocoes') => { try { const result = await api.learn({ messageId: message.id, text: textOf(message), label }); setLearning((old) => ({ ...(old || {}), feedback: (old?.feedback || 0) + 1 })); setPredictions((old) => ({ ...old, [message.id]: { category: label, confidence: 1, details: [] } })); setSelected((old) => old?.id === message.id ? { ...old, classification: { category: label, confidence: 1, details: [] } } : old); setNotice(`Aprendido: esta mensagem foi registrada como ${label === 'promocoes' ? 'propaganda' : label}. ${result.samples} exemplos usados no treino.`); } catch (e) { setError(e.message); } };
  const trainNow = async () => { try { setNotice('Treinando com os exemplos confirmados…'); const result = await api.runLearning(); setLearning((old) => ({ ...(old || {}), feedback: result.feedback })); setNotice(`Treinamento concluído com ${result.samples} exemplos.`); } catch (e) { setError(e.message); } };
  const deletePromotional = async () => { const promotional = messages.filter((message) => isRedCategory(predictions[message.id]?.category)); if (!promotional.length) { setNotice('Não há mensagens vermelhas para excluir.'); return; } if (!window.confirm(`Excluir permanentemente ${promotional.length} mensagem(ns) vermelha(s) classificadas como propaganda ou não importantes?`)) return; setBulkDeleting(true); setError(''); try { const result = await api.deletePromotionalMessages(); const deletedIds = new Set(result.ids || promotional.map((message) => message.id)); setMessages((all) => all.filter((message) => !deletedIds.has(message.id))); setPredictions((all) => Object.fromEntries(Object.entries(all).filter(([id]) => !deletedIds.has(id)))); if (selected && deletedIds.has(selected.id)) setSelected(null); setNotice(`${result.deleted} mensagem(ns) vermelha(s) excluída(s) permanentemente.`); } catch (e) { setError(e.message); } finally { setBulkDeleting(false); } };
  if (!auth) return <div className="center">Carregando…</div>;
  if (!auth.authenticated) return <main className="landing"><div className="brand">mail<span>desk</span></div><AuthPanel onAuthenticated={() => api.status().then(setAuth)} /></main>;
  return <div className="app"><header><div className="brand">mail<span>desk</span></div><div className="account"><span>{auth.account}</span><button onClick={async () => { await api.logout(); setAuth({ authenticated: false }); }}>Sair</button></div></header><div className="toolbar"><div><div className="eyebrow">CAIXA DE ENTRADA INTELIGENTE</div><h2>{messages.length} mensagens</h2><p className="subline">Vermelho = propaganda ou não importante · feedback confirmado alimenta o modelo</p></div><div className="toolbar-actions"><button className="refresh" onClick={load} disabled={loading || bulkDeleting}>Atualizar</button><button className="bulk-delete" onClick={deletePromotional} disabled={loading || bulkDeleting}>{bulkDeleting ? 'Excluindo…' : 'Excluir vermelhos'}</button><button className="train" onClick={trainNow} disabled={bulkDeleting}>Treinar agora</button></div></div>{(error || notice) && <div className={error ? 'notice error' : 'notice'}>{error || notice}</div>}<div className="content"><aside>{loading ? <div className="empty">Buscando e classificando mensagens…</div> : messages.length === 0 ? <div className="empty">Sua caixa está vazia.</div> : messages.map((m) => { const prediction = predictions[m.id]; const red = isRedCategory(prediction?.category); return <article key={m.id} className={`mail ${!m.isRead ? 'unread' : ''} ${red ? 'promotional' : ''} ${selected?.id === m.id ? 'selected' : ''}`} onClick={() => open(m.id)}><div className="mail-top"><strong>{sender(m)}</strong><time>{formatDate(m.receivedDateTime)}</time></div><h3>{m.subject || '(sem assunto)'}</h3><p>{m.bodyPreview || 'Sem prévia disponível'}</p><div className="mail-label">{prediction ? `${prediction.category}${prediction.confidence ? ` · ${Math.round(prediction.confidence * 100)}%` : ''}` : 'classificando…'}</div><div className="mail-actions">{red && <button className="learn-small" onClick={(e) => { e.stopPropagation(); teach(m); }}>É propaganda</button>}<button aria-label="Excluir e-mail" onClick={(e) => { e.stopPropagation(); remove(m.id); }}>×</button></div></article>; })}</aside><section className="detail">{selected ? <><div className="detail-top"><div className="eyebrow">MENSAGEM · {selected.classification?.category || 'sem classificação'}</div><h1>{selected.subject || '(sem assunto)'}</h1><p>De <strong>{sender(selected)}</strong> · {formatDate(selected.receivedDateTime)}</p></div><div className="body" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(selected.body?.content || '<p>Sem conteúdo.</p>') }} /><div className="detail-actions"><button className="learn" onClick={() => teach(selected)}>É propaganda / não importante</button><button className="danger" onClick={() => remove(selected.id)}>Excluir e-mail</button></div></> : <div className="empty detail-empty">Selecione uma mensagem para ler.</div>}</section></div><footer>{learning?.feedback || 0} feedbacks confirmados · aprendizado diário ativo</footer></div>;
}
